
FROM centos:centos8
MAINTAINER Remy Zyngfogel <r.zyngfogel@calypso.science>

RUN yum update -y

RUN yum -y install epel-release &&\
    yum -y install git vim sudo tar unzip wget gcc\
                   python3-pip python3-devel MySQL-python3\
                   openssh-server initscripts &&\
    yum clean all


RUN echo "-----------------Install yum stuff-----------------"
RUN yum -y install dnf-plugins-core
RUN dnf config-manager --set-enabled PowerTools 
RUN yum -y update
RUN yum -y install autoconf automake gcc gcc-c++ gcc-gfortran make unzip patch &&\
    yum -y install openssl-devel bzip2-devel libffi libffi-devel &&\
    yum -y install netcdf netcdf-devel hdf5 hdf hdf-devel nco &&\
    yum -y update && yum clean all

RUN yum -y install cmake gcc-gfortran libpng-devel libjpeg-devel libxml2-devel libxslt-devel sqlite &&\
    yum -y install sqlite-devel bzip2-devel gdbm-devel openssl-devel tcl-devel tk-devel expat-devel &&\
    yum -y install libffi-devel gcc-c++ mesa-libGL-devel mesa-libGLU-devel libXt-devel automake bzip2 ncurses-devel cmake 


RUN pip3 install pathlib

RUN echo "-----------------Install PySCHISM -----------------" &&\
    cd /usr/src/ &&\
    git clone https://github.com/schism-dev/pyschism 

RUN pip3 install Cython pyproj==2.4.2

ENV PROJ_DIR /usr/local

RUN cd /usr/src/pyschism &&\
    pip3 install .


RUN echo "-----------------Install PIP stuff -----------------"

RUN pip3 install pyyaml mako gnureadline


RUN echo "-----------------Install ttide-----------------" &&\
    cd /usr/src/ &&\
    git clone https://github.com/moflaher/ttide_py &&\
    cd /usr/src/ttide_py/ &&\
    pip3 install .


RUN cd /usr/local/lib/python3.6/site-packages/pyschism/mesh/ &&\
    sed -i "s|            for IDtags in geom.values():|#            for IDtags in geom.values()|g" base.py &&\   
    sed -i "s|                for IDtag in IDtags:|#                for IDtag in IDtags:|g" base.py &&\  
    sed -i "s|                    print('IDtag in self.coords_id, msg')|#                    print('IDtag in self.coords_id, msg')|g" base.py


##    sed -i "s|assert IDtag in self.coords_id, msg|print('IDtag in self.coords_id, msg')|g" base.py


RUN yum -y install udunits2-devel
RUN yum -y install proj proj-devel
RUN echo "-----------------Install CDO-----------------" &&\
    cd /usr/src/ &&\
    wget https://code.mpimet.mpg.de/attachments/download/20826/cdo-1.9.8.tar.gz &&\
    tar -zxvf cdo-1.9.8.tar.gz &&\
    cd cdo-1.9.8 &&\
    ./configure --with-netcdf --with-jasper --with-hdf5  --with-udunits2 &&\
    make &&\
    make install


RUN pip3 install xarray

RUN cd /usr/local/lib/python3.6/site-packages/pyschism/mesh/ &&\
    sed -i "s|                    assert IDtag in self.coords_id, msg|#                    assert IDtag in self.coords_id, msg|g" base.py 



RUN cd /usr/src/ &&\
    git clone https://github.com/calypso-science/schism.git 

RUN pip3 install descartes

RUN pip3 install motuclient


## TO CHANGE
#/opt/conda/envs/schism/lib/python3.6/site-packages/pyschism/driver/driver.py



#RUN cd /usr/src/ &&\
#    git clone https://github.com/CADWRDeltaModeling/vtools.git &&\
#    git checkout vtools-py3 &&\
#    pip3 install .


